name: rainbow trader
favicon: null
layout_spectrum: 0.7478
typography_spectrum: 0.35679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13816510047763586
  lightness: 0.17346203280612826
  saturation: 0.5563222754281014
  rhythmicContrast: 0.5007559105288237
purpose: []
